title: My Site
name: My linked notebook
user_description: notenote.link
notes_url: "https://krishna8009.github.io"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: MIT
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://krishna8009.github.io" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8
description: >- # this means to ignore newlines until "baseurl:"
  My jar of 

# Build settings
#remote_theme: "dracula/gh-pages"
plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-redirect-from

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: null
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge


sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

toc:
  max_level: 3

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
